### ISSUE TITLE
Action failing

### ISSUE THREAD

**Issue by Catatomik** [jpb06/coverage-badges-action#127]
Actions fails at the beginning when running `/usr/bin/git checkout mc-no-local-pruning`, with the error:
```
error: pathspec 'mc-no-local-pruning' did not match any file(s) known to git
```
Example [here](https://github.com/Cata-Dev/RAPTOR/actions/runs/15852314950/job/44689522089).

This is [my workflow file](https://github.com/Cata-Dev/RAPTOR/pull/208/commits/f689ed0d228c2106e866df6e06104a50af422956):
```yml
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev, no-local-pruning]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm run --if-present build

  test:
    needs: build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm run --if-present test

      - name: Generating coverage badges
        uses: jpb06/coverage-badges-action@latest
        with:
          # Branches are filtered through triggers
          branches: "*"
          badges-icon: jest
          badges-labels-prefix: "Coverage: "
```
