### ISSUE TITLE
1.3.2 is failing silently

### ISSUE THREAD

**Issue by mateothegreat** [jpb06/coverage-badges-action#130]
1.3.2 is failing silently but showing the actual code of the build output script?

See: https://github.com/mateothegreat/svelte5-router/actions/runs/15867203450/job/44736264609#step:8:12

![Image](https://github.com/user-attachments/assets/2ae675c8-ce27-41a6-879a-72c7f8da4464)

Called with:

```yaml
- name: ⚙️ Generating coverage badges
  uses: jpb06/coverage-badges-action@v1.3.2
  with:
    branches: "*"
    badges-labels-prefix: "Test Coverage"
    badges-icon: vitest
    coverage-summary-path: tmp/coverage/coverage-summary.json
    output-folder: docs/assets
```

🙏
