### ISSUE TITLE
Coverage badge changes even if no code changes

### ISSUE THREAD

**Issue by benmoveai** [jpb06/coverage-badges-action#21]
Hi,

I'm just trying to get some guidance on figuring out why this happens. We have the following workflow in github.

* Push changes and create a PR
* workflow runs on PR creation

Within the workflow we have the following:
```
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup, run vitest and generate coverage report
        uses: ./.github/actions/vitest
      - run: |
          git fetch origin ${GITHUB_HEAD_REF}
      - name: Generating coverage badges
        uses: jpb06/coverage-badges-action@latest
        with:
          branches: "*"
          commit-user-email: "github-actions[bot]@users.noreply.github.com"
          commit-user: "github-actions[bot]"
```

`coverage-badges-action` then commits the updated coverage badges back to the PR, as expected.

However, if we then make a change to a non-JS file (i.e. the readme) and push we find that he coverage badges change again - by a tiny amount, i.e. 92.16% to 92.08%. This can get us stuck in a loop where the coverage badges are always updating - even if no JS code has changed.

My assumption here is that whatever algorithm is calculating the code coverage is just counting lines slightly differently on different pushes.

Is there any way around this? My initial thought was that if we could just make the coverage badge use whole numbers (i.e. 92%) which I think could remove a lot of this problem.

Any input you can provide here would be great. 

Thanks
