### ISSUE TITLE
Accept multiple lines for coverage-summary-path

### ISSUE THREAD

**Issue by SirPhemmiey** [jpb06/coverage-badges-action#5]
https://github.com/jpb06/jest-badges-action/issues/62#issue-2315168420

**Comment by jpb06** [comment]
> Hello,
> 
> Thanks for this action.
> 
> I am using this action in a monorepo workflow and i'd like to generate a badge for some specific apps in the monorepo.
> 
> Instead of specifying an action multiple times for different projects as in :
> 
> ```
> - name: Generating app-1 coverage badges
>         uses: jpb06/jest-badges-action@latest
>         with:
>           coverage-summary-path: apps/app-1/coverage/coverage-summary.json
> 
> - name: Generating app-2 coverage badges 
>         uses: jpb06/jest-badges-action@latest
>         with:
>           coverage-summary-path: apps/app-2/coverage/coverage-summary.json
> ```
> 
> Can it not be possible like this:
> 
> ```
> - name: Generating coverage badges
>         uses: jpb06/jest-badges-action@latest
>         with:
>           coverage-summary-path: |
>                 apps/app-1/coverage/coverage-summary.json
>                apps/app-2/coverage/coverage-summary.json
> ```
> 
> Or probably pass a wildcard path to it like this:
> 
> ```
> - name: Generating coverage badges
>         uses: jpb06/jest-badges-action@latest
>         with:
>           coverage-summary-path: |
>                 apps/**/coverage-summary.json
> ```
> 
> Looking forward for your response on this

Hello!

Yes that's a good idea. I will tweak the action this week-end to address your need.

**Comment by SirPhemmiey** [comment]
Yes, thanks. In addition to that, i'm wondering if it'll make sense to also have the output like so:

```
badges/app-1/*
```
So that in the readme, we can just pull the svg content and display it or do whatever we want with it.

**Comment by jpb06** [comment]
You're right!
If we have several inputs, we will necessarily have several outputs.

What we could do is also generating an average set of badges for all apps/libs. For example, if I have two apps with `55%` and `30%` coverage respectively, I'd have an average of `42.5%` for the repo.
These average badges could be saved at `badges/average/*`.

**Comment by jpb06** [comment]
Thinking about it, the array pattern with glob paths is probably the most flexible for input. eg something like:

```yml
    [...]
    - name: ⚙️ Generating coverage badges
      uses: jpb06/coverage-badges-action@latest
        with:
          coverage-summary-path: 
          - ./apps/**/coverage/coverage-summary.json
          - ./libs/**/coverage/coverage-summary.json
```

**Comment by SirPhemmiey** [comment]
> You're right! If we have several inputs, we will necessarily have several outputs.
> 
> What we could do is also generating an average set of badges for all apps/libs. For example, if I have two apps with `55%` and `30%` coverage respectively, I'd have an average of `42.5%` for the repo. These average badges could be saved at `badges/average/*`.

Yes! Calculating the average and putting it in `badges/average/*` would be a great add-on for sure!

**Comment by jpb06** [comment]
Aight, thanks for input, I well have a look tomorrow.

**Comment by jpb06** [comment]
https://github.com/jpb06/node-coverage-badges/pull/2

**Comment by jpb06** [comment]
https://github.com/jpb06/coverage-badges-action/pull/8

**Comment by SirPhemmiey** [comment]
@jpb06 can you let me know when it's released? 

Thanks!

**Comment by jpb06** [comment]
Sure thing. Sorry, I have a rough week ahead. I will try to get it done asap.

**Comment by SirPhemmiey** [comment]
No worries man, thank you!

**Comment by jpb06** [comment]
I did a manual test with these args, in case it can help you:

```yaml
     # ...

      - name: ⚙️ Generating coverage badges
        uses: ./
        with:
          branches: multiple-summary-paths
          coverage-summary-path: |
            ./coverage/coverage-summary.json
            ./apps/**/coverage/coverage-summary.json
          no-commit: true
```

**Comment by SirPhemmiey** [comment]
Hey @jpb06 , thank you so much!!!

Where is the output location going to be? And is it going to output the badges in separate locations?

**Comment by jpb06** [comment]
default is `./badges/{subpath}/*`, assuming the wildcard glob paths end with `/coverage/coverage-summary.json`.

So for example if you have these files:
- ./apps/front/coverage/coverage-summary.json
- ./apps/back/coverage/coverage-summary.json

Then the output would be:
- ./badges/front/*
- ./badges/back/*

**Comment by SirPhemmiey** [comment]
Sweet, thank you! 

I'll try it out today or tomorrow and get back to you!

Thanks, once again!

**Comment by jpb06** [comment]
There is an issue with subpath extraction from glob paths:
https://github.com/jpb06/coverage-badges-action/pull/10

On it.

**Comment by SirPhemmiey** [comment]
Hey @jpb06  ,

Do you know what could be wrong here? After `git add ./badges`, why it it finding nothing staged to commit? Also, how does committing work? Does it commit to the target branch (`badges`) and then i have to open a PR from there to the protected branch that i have? 

See a screenshot:

<img width="1051" alt="Screenshot 2024-06-03 at 11 10 21" src="https://github.com/jpb06/coverage-badges-action/assets/22390818/0cfa295c-ad05-42b2-bc2c-85904dc49f75">

**Comment by jpb06** [comment]
Hello! Sorry for getting back to you this late. I finally got some time to find the root of the issue. It should be working fine now.

I made some [manual tests](https://github.com/jpb06/coverage-badges-action/actions/workflows/generate-badges-from-several-subpath.yml) using the following action:
```yaml
name: ⚡ Generate badges from several subpaths	

on:	
  push:	
    branches:	
      - test-glob-path # just restricting the run on the test branch

jobs:	
  coverage-badges-generation:	
    name: 📣 Coverage badges generation	
    runs-on: ubuntu-latest	
    timeout-minutes: 10	
    steps:	
      - name: 🛑 Cancel Previous Runs	
        uses: styfle/cancel-workflow-action@0.12.1	

      - name: ⬇️ Checkout repo	
        uses: actions/checkout@v4	
        with:	
          fetch-depth: 0	

      - name: 📦 Setup pnpm	
        uses: pnpm/action-setup@v4	
        with:	
          version: latest	

      - name: ⎔ Setup node	
        uses: actions/setup-node@v4	
        with:	
          node-version-file: '.node-version'	
          registry-url: 'https://registry.npmjs.org'	
          cache: 'pnpm'	
          cache-dependency-path: ./package.json	

      - name: 📥 Install deps	
        run: pnpm install --frozen-lockfile	

      - name: 🔍 Tests	
        run: pnpm test-ci	

      - name: ⚙️ Generating coverage badges	
        uses: ./	
        with:	
          branches: test-glob-path # just restricting the run on the test branch
          coverage-summary-path: |	
            ./coverage/coverage-summary.json		
            ./apps/**/coverage/coverage-summary.json	
          badges-icon: vitest	
```

--

By default badges are pushed to the current branch. You can also use the [target branch](https://github.com/jpb06/coverage-badges-action?tab=readme-ov-file#-target-branch) parameter to define on which branch badges should be pushed.

Could you try again with v.1.0.8 and let me know if this is fixed for you?

Thanks.

**Comment by SirPhemmiey** [comment]
Hi, thanks for working on this. 

I'll try it soon and let you know. Are you saying that I can open a PR in `branch A` to be merged into `main`, run this workflow, and instruct it to push badges to the `main` branch?

**Comment by jpb06** [comment]
Just so you know, there was a bundling issue with `v1.0.8`. Please use `v.1.0.9` or `latest` 🙇🏻

**Comment by SirPhemmiey** [comment]
Hello, i'm using `latest` and i'm having this error

```
🚀 Generating badges ...
🚀 Pushing badges to the repo
/usr/bin/git config --global user.name SirPhemmiey
/usr/bin/git config --global user.email SirPhemmiey@users.noreply.github.com
/usr/bin/git checkout badge-base
Switched to branch 'badge-base'
M	badges/coverage-branches.svg
M	badges/coverage-functions.svg
D	badges/coverage-jest coverage.svg
M	badges/coverage-lines.svg
M	badges/coverage-statements.svg
Your branch is up to date with 'origin/badge-base'.
/usr/bin/git status
On branch badge-base
Your branch is up to date with 'origin/badge-base'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   badges/coverage-branches.svg
	modified:   badges/coverage-functions.svg
	deleted:    badges/coverage-jest coverage.svg
	modified:   badges/coverage-lines.svg
	modified:   badges/coverage-statements.svg

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	badges/coverage-total.svg

no changes added to commit (use "git add" and/or "git commit -a")
/usr/bin/git add ./badges
/usr/bin/git commit -m chore: Updating coverage badges [skip ci]
→ No staged files match any configured task.
⧗   input: chore: Updating coverage badges [skip ci]
✖   subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]

✖   found 1 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

husky - commit-msg hook exited with code 1 (error)

🫠  1 error occured

💥  github-action-error  • Error: The process '/usr/bin/git' failed with exit code 1

ℹ️  Consider using spans to improve errors reporting.

🚨 Node Stacktrace
│ at catch (/home/runner/work/_actions/jpb06/coverage-badges-action/latest/dist/index.js:1:2982)
│ at /home/runner/work/_actions/jpb06/coverage-badges-action/latest/dist/index.js:1:784[26](https://github.com/<redacted>/<redacted>/actions/runs/9485362144/job/26137100457#step:11:27)7
│ at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

node:internal/process/promises:[28](https://github.com/<redacted>/<redacted>/actions/runs/9485362144/job/26137100457#step:11:29)9
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ❌ runPromise failure] {
  name: '(FiberFailure) Error',
  [Symbol(effect/Runtime/FiberFailure)]: Symbol(effect/Runtime/FiberFailure),
  [Symbol(effect/Runtime/FiberFailure/Cause)]: { _tag: 'Fail', error: '❌ runPromise failure' }
}
```

Here's how i m using it:

```
- name: 'Generating coverage badges'
        uses: jpb06/coverage-badges-action@latest
        with:
          branches: '*'
          commit-message: 'chore: Updating coverage badges [skip ci]'
          coverage-summary-path: |
            specific_projects/apps/**/coverage-summary.json
          no-commit: false
```

**Comment by SirPhemmiey** [comment]
@jpb06

**Comment by jpb06** [comment]
```
⧗   input: chore: Updating coverage badges [skip ci]
✖   subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]

✖   found 1 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

husky - commit-msg hook exited with code 1 (error)
```

Your commit hook config is not accepting commit messages with a subject starting with a capital letter. Try:

```yaml
     - name: 'Generating coverage badges'
        uses: jpb06/coverage-badges-action@latest
        with:
          branches: '*'
          commit-message: 'chore: updating coverage badges [skip ci]'
          coverage-summary-path: |
            specific_projects/apps/**/coverage-summary.json
          no-commit: false
```

cf https://github.com/conventional-changelog/commitlint/issues/2113
